// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6zEItJtfM93RwgaFPLZL6enhffpTgkCw',
    appId: '1:190829614699:web:0f0cf14828ecf12be9c32e',
    messagingSenderId: '190829614699',
    projectId: 'login-demo-challange',
    authDomain: 'login-demo-challange.firebaseapp.com',
    storageBucket: 'login-demo-challange.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrduEEXPtqxbM2p68-oI9hUX0DA5RBCFA',
    appId: '1:190829614699:android:93d5c3d30323d241e9c32e',
    messagingSenderId: '190829614699',
    projectId: 'login-demo-challange',
    storageBucket: 'login-demo-challange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bPH8jmUpmUUvKzReVn2yTVG69eHybC4',
    appId: '1:190829614699:ios:4ad2fba8bb491440e9c32e',
    messagingSenderId: '190829614699',
    projectId: 'login-demo-challange',
    storageBucket: 'login-demo-challange.appspot.com',
    iosClientId: '190829614699-gs0o3htv8rcu92g17cipcjtc31v58p3s.apps.googleusercontent.com',
    iosBundleId: 'login',
  );
}
